name: newrelic-alert-cloudformation-resource
title: CloudFormation custom Resource that creates New Relic NRQL Alerts
description: |
  Custom CloudFormation Resource that allows for the creation of New Relic NRQL Alerts as part of a CloudFormation Stack. 

summary: |
  CloudFormation custom Resource that creates New Relic NRQL Alerts

logo: logo.jpg
level: Community

website: https://aws.amazon.com/cloudformation/

keywords:
  - nrlabs
  - nrlabs-data
  - aws
  - cloudformation
  - alerts

authors:
  - New Relic Labs

documentation:
  - name: Resource installation and configuration documentation
    description: |
      Installation and configuration instructions
    url: https://github.com/newrelic-experimental/newrelic-alerts-cloudformation
